export const FETCH_ORDERS_BEGIN   = 'FETCH_ORDERS_BEGIN';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_ITEMS_BEGIN   = 'FETCH_ITEMS_BEGIN';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_ITEMS_PER_ORDER_BEGIN   = 'FETCH_ITEMS_PER_ORDER_BEGIN';
export const FETCH_ITEMS_PER_ORDER_SUCCESS = 'FETCH_ITEMS_PER_ORDER_SUCCESS';
export const FETCH_ITEMS_PER_ORDER_FAILURE = 'FETCH_ITEMS_PER_ORDER_FAILURE';

export const ADD_NEW_ITEM_CURRENT_ORDER = 'ADD_NEW_ITEM_CURRENT_ORDER'
export const UPDATE_ITEM_QUANTITY_CURRENT_ORDER = 'UPDATE_ITEM_QUANTITY_CURRENT_ORDER'
export const UPDATE_ITEM_ID_CURRENT_ORDER = 'UPDATE_ITEM_ID_CURRENT_ORDER'
export const REMOVE_ITEM_CURRENT_ORDER = 'REMOVE_ITEM_CURRENT_ORDER'

export const UPDATE_ORDER_BEGIN = 'UPDATE_ORDER_BEGIN'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE'

export const DELETE_ORDER_BEGIN = 'DELETE_ORDER_BEGIN'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE'

export const ADD_NEW_ORDER_BEGIN = 'ADD_NEW_ORDER_BEGIN'
export const ADD_NEW_ORDER_SUCCESS = 'ADD_NEW_ORDER_SUCCESS'
export const ADD_NEW_ORDER_FAILURE = 'ADD_NEW_ORDER_FAILURE'

export const AUTHENTICATE_USER = 'AUTHENTICATE_USER'
export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS'
export const AUTHENTICATE_USER_FAILURE = 'AUTHENTICATE_USER_FAILURE'

export const VERIFY_TOKEN = 'VERIFY_TOKEN'
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS'
export const VERIFY_TOKEN_FAILURE = 'VERIFY_TOKEN_FAILURE'
export const LOG_OUT_USER = 'LOG_OUT_USER'